In [1]:
import pandas as pd 
import geopandas as gpd

In [3]:
# Load and read data 
neighborhoodJSON = './dallas_coordinates.json'
housesCSV = './houses.csv'

houses = pd.read_csv(housesCSV)
neighborhoods = gpd.read_file(neighborhoodJSON)

In [6]:
# convert lat/lng data to geometry with gpd 
gdp_df = gpd.GeoDataFrame(
    houses,   geometry=gpd.points_from_xy(houses.lng, houses.lat))
gdp_df

,Unnamed: 0,address,price,city,state,zipcode,beds,baths,size,type,lat,lng,geometry
0,0,2226 Pecan Grove Ct,503900,Dallas,TX,75228,3,3,2434,House,32.811456,-96.703775,POINT (-96.70377 32.81146)
1,1,9615 Limestone Dr,145000,Dallas,TX,75217,3,2,1057,House,32.744224,-96.656066,POINT (-96.65607 32.74422)
2,2,2714 Burger Ave,155000,Dallas,TX,75215,3,2,912,House,32.764402,-96.763974,POINT (-96.76397 32.76440)
3,3,351 Crenshaw Dr,199000,Dallas,TX,75217,4,2,1360,House,32.706745,-96.655701,POINT (-96.65570 32.70674)
4,4,2212 Lowery St,265000,Dallas,TX,75215,3,2,1366,House,32.743627,-96.757222,POINT (-96.75722 32.74363)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
648,648,10226 Pinecrest Dr,249000,Dallas,TX,75228,2,1,988,House,32.833550,-96.685872,POINT (-96.68587 32.83355)
649,649,3458 Saint Cloud Cir,450000,Dallas,TX,75229,3,2,2331,House,32.907627,-96.862018,POINT (-96.86202 32.90763)
650,650,5505 Charlestown Dr,1495000,Dallas,TX,75230,5,5,4897,House,32.917888,-96.816164,POINT (-96.81616 32.91789)
651,651,8435 Coppertowne Ln,325000,Dallas,TX,75243,3,2,1855,Townhouse,32.895364,-96.727046,POINT (-96.72705 32.89536)
652,652,4620 Munger Ave #103,409900,Dallas,TX,75204,2,3,1590,Condo,32.805272,-96.780223,POINT (-96.78022 32.80527)

In [11]:
# join with shape file 
join = gpd.sjoin(gdp_df, neighborhoods)
join

<ipython-input-11-e9ef0aba2189>:1: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:4326

  join = gpd.sjoin(gdp_df, neighborhoods)

,Unnamed: 0,address,price,city,state,zipcode,beds,baths,size,type,lat,lng,geometry,index_right,name,cartodb_id,created_at,updated_at
0,0,2226 Pecan Grove Ct,503900,Dallas,TX,75228,3,3,2434,House,32.811456,-96.703775,POINT (-96.70377 32.81146),4,East Dallas,4.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
21,21,719 Parkhurst Dr,399000,Dallas,TX,75218,3,2,1446,House,32.849673,-96.706613,POINT (-96.70661 32.84967),4,East Dallas,4.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
25,25,11318 Aledo Dr,230000,Dallas,TX,75228,3,2,1312,House,32.849374,-96.680053,POINT (-96.68005 32.84937),4,East Dallas,4.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
31,31,2338 Pinebluff Dr,425000,Dallas,TX,75228,3,3,2138,House,32.806073,-96.706345,POINT (-96.70634 32.80607),4,East Dallas,4.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
74,74,3322 Crest Ridge Dr,215000,Dallas,TX,75228,3,2,1269,House,32.828649,-96.659557,POINT (-96.65956 32.82865),4,East Dallas,4.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,385,4949 Skillman St APT 254,178900,Dallas,TX,75206,2,2,1136,Condo,32.846840,-96.761427,POINT (-96.76143 32.84684),9,Upper Greenville,9.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
387,387,4800 Northway Dr APT 15A,220000,Dallas,TX,75206,2,2,991,Condo,32.846696,-96.768813,POINT (-96.76881 32.84670),9,Upper Greenville,9.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
426,426,5609 Smu Blvd APT 301,349000,Dallas,TX,75206,2,2,1217,Condo,32.842009,-96.772217,POINT (-96.77222 32.84201),9,Upper Greenville,9.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
439,439,5111 Skillman St #229,204900,Dallas,TX,75206,2,2,1057,Townhouse,32.848678,-96.761245,POINT (-96.76125 32.84868),9,Upper Greenville,9.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00
504,504,5609 Smu Blvd APT 509,318000,Dallas,TX,75206,2,2,1025,Condo,32.842009,-96.772217,POINT (-96.77222 32.84201),9,Upper Greenville,9.0,2013-06-24T21:20:04.519000+00:00,2013-06-24T21:20:04.764000+00:00

In [13]:
# Clean 
join = join.drop(columns=['Unnamed: 0','index_right', 'cartodb_id', 'created_at', 'updated_at'])

In [14]:
join.to_csv('./joined.csv')